pipeline {
 agent {
    kubernetes {
      cloud 'openshift'
      yaml """
        apiVersion: v1
        kind: Pod
        spec:
          serviceAccountName: jenkins-agent
          containers:
          - name: builder
            image: nebbog/builder:1.6.0
            command:
            - cat
            tty: true
            volumeMounts:
            - name: home-volume
              mountPath: /home/jenkins
            env:
            - name: HOME
              value: /home/jenkins
          volumes:
          - name: home-volume
            emptyDir: {}
       """
    }
  }

  stages {
 
   stage('Build Java project - demo-app') {
     steps{
       container('builder') {
         script {
           sh 'cd ci-cd;./build.sh'
         }
       }
     }
   }

  stage('Preparing demo-app for tomcat image') {
     steps{
       container('builder') {
         script {
           sh 'cd ci-cd/docker;./prepare-app-for-image.sh'
         }
       }
     }
   }
  
  stage('Build image using buildconfigs: my-demo-app-image') {
    steps{
      container('builder') {
        sh 'curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz"'
        sh 'tar -zxvf oc.tar.gz;./oc version'
        sh 'ls -lrth'
        sh 'chmod a+x ./oc;cp ./oc /tmp'
        sh 'ls -lrth /tmp'
        sh 'echo $PATH'
      }
    }
  }

   
 }
}
