pipeline {
  agent {
    kubernetes {
      inheritFrom 'nebbog/builder:1.2.0'
    }
  }

  stages {
 
   stage('Build Java project - demo-app') {
     steps{
       container('builder') {
         script {
           sh 'cd ci-cd;./build.sh'
         }
       }
     }
   }

   
 }
}
